/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hustik.magmageo.tela.cadastro;

import br.com.hustik.magmageo.database.BancoDeDados;
import javax.swing.JOptionPane;

/**
 *
 * @author Hustik
 */
public class CadastroTipoOcorrencia extends javax.swing.JDialog {

    private final CadastroOcorrencia cadOcorr;
    private final BancoDeDados bd;

    /**
     * Creates new form CadastroTipoOcorrencia
     *
     * @param parent
     * @param modal
     * @param cadOc
     * @param bd
     */
    public CadastroTipoOcorrencia(java.awt.Dialog parent, boolean modal, CadastroOcorrencia cadOc, BancoDeDados bd) {
        super(parent, modal);
        initComponents();
        pack();
        this.cadOcorr = cadOc;
        this.getRootPane().setDefaultButton(jButtonCadastrarTipoOcorrencia);
        this.bd = bd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldTipoOcorrencia = new javax.swing.JTextField();
        jButtonCadastrarTipoOcorrencia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCadastrarTipoOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hustik/magmageo/icons/Add-Point_16x16.png"))); // NOI18N
        jButtonCadastrarTipoOcorrencia.setText("Cadastrar");
        jButtonCadastrarTipoOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarTipoOcorrenciaActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTipoOcorrencia)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarTipoOcorrencia))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(jTextFieldTipoOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarTipoOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Tipo de Ocorrência");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarTipoOcorrenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCadastrarTipoOcorrenciaActionPerformed
    {//GEN-HEADEREND:event_jButtonCadastrarTipoOcorrenciaActionPerformed
        boolean error = false;
        String descricao = jTextFieldTipoOcorrencia.getText();
        //Verificar campos em branco
        if (descricao.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o tipo da ocorrência.");
            jTextFieldTipoOcorrencia.requestFocus();
            error = true;
        }
        //Realizar cadastro
        if (!error) {
            //Inserir tipo no banco de dados
            if (bd.cadastroTipoOcorrencia(descricao)) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                //Atualizar JComboBoxTipoOcorrencia
                cadOcorr.updateTipoOCorrencia();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar tipo.");
                jTextFieldTipoOcorrencia.requestFocus();
            }
        }
    }//GEN-LAST:event_jButtonCadastrarTipoOcorrenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarTipoOcorrencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldTipoOcorrencia;
    // End of variables declaration//GEN-END:variables
}
