/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hustik.magmageo.tela.cadastro;

import br.com.hustik.magmageo.database.BancoDeDados;
import br.com.hustik.magmageo.model.TipoOcorrencia;
import br.com.hustik.magmageo.tela.MagmaGeo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rômulo Goelzer Portolann
 * @university UNIVALI - Universidade do Vale do Itajái
 */
public class CadastroOcorrencia extends javax.swing.JDialog {

    private final MagmaGeo telaPrincipal;
    private boolean alteracao = false;
    private final BancoDeDados bd;
    private ArrayList<TipoOcorrencia> tipos;
    /**
     * Creates new form CadastroOcorrencia
     *
     * @param parent
     * @param modal
     * @param telaPrinc
     * @param bd
     */
    public CadastroOcorrencia(java.awt.Frame parent, boolean modal, MagmaGeo telaPrinc, BancoDeDados bd) {
        super(parent, modal);
        initComponents();
        pack();
        this.telaPrincipal = telaPrinc;
        this.getRootPane().setDefaultButton(jButtonCadastrarOcorrencia);
        this.bd = bd;
        updateTipoOCorrencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLongitude = new javax.swing.JTextField();
        jTextFieldLatitude = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonCadastrarOcorrencia = new javax.swing.JButton();
        jComboBoxTipoOcorrencia = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonCadastrarTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Ocorrência");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel2.setText("Longitude (x)");

        jLabel3.setText("Latitude (y)");

        jLabel4.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonCadastrarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hustik/magmageo/icons/Add-Point_16x16.png"))); // NOI18N
        jButtonCadastrarOcorrencia.setText("Cadastrar");
        jButtonCadastrarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarOcorrenciaActionPerformed(evt);
            }
        });

        jComboBoxTipoOcorrencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipoOcorrencia.setName(""); // NOI18N
        jComboBoxTipoOcorrencia.setPreferredSize(new java.awt.Dimension(56, 25));

        jLabel5.setText("Tipo:");

        jButtonCadastrarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hustik/magmageo/icons/Add_16.png"))); // NOI18N
        jButtonCadastrarTipo.setMaximumSize(new java.awt.Dimension(99, 25));
        jButtonCadastrarTipo.setMinimumSize(new java.awt.Dimension(99, 25));
        jButtonCadastrarTipo.setPreferredSize(new java.awt.Dimension(99, 25));
        jButtonCadastrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldLatitude)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarOcorrencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoOcorrencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonCadastrarOcorrencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarOcorrenciaActionPerformed
        boolean error = false;
        String descricao = jTextAreaDescricao.getText();
        int    id_tipo   = tipos.get(jComboBoxTipoOcorrencia.getSelectedIndex()).getID();
        String longitude = jTextFieldLongitude.getText();
        String latitude  = jTextFieldLatitude.getText();
        //Verificar campos em branco
        if (id_tipo == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione o tipo da ocorrência.");
            jComboBoxTipoOcorrencia.requestFocus();
            error = true;
        } else if (longitude.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, informe a longitude.");
            jTextFieldLongitude.requestFocus();
            error = true;
        } else if (latitude.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, informe a latitude.");
            jTextFieldLatitude.requestFocus();
            error = true;
        }
        //Realizar cadastro
        if (!error) {
            alteracao = true;
            //Inserir ocorrência no banco de dados
            String geometria = longitude + " " + latitude;
            if (bd.cadastroOcorrencia(descricao, id_tipo, geometria)) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                //Atualizar tabela de ocorrências
                telaPrincipal.updateOccourrencesTable();
                resetComponents();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar ocorrência.");
                jComboBoxTipoOcorrencia.requestFocus();
            }
            
            
        }
        //Verificar se o ponto inserido está dentro de alguma área de algum bairro
    }//GEN-LAST:event_jButtonCadastrarOcorrenciaActionPerformed

    private void jButtonCadastrarTipoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCadastrarTipoActionPerformed
    {//GEN-HEADEREND:event_jButtonCadastrarTipoActionPerformed
        CadastroTipoOcorrencia cadTipoOcorr = new CadastroTipoOcorrencia(this, true, this, bd);
        cadTipoOcorr.setLocationRelativeTo(this);
        cadTipoOcorr.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarTipoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        if (alteracao) {
            telaPrincipal.updateOccourrencesTable();
        }
    }//GEN-LAST:event_formWindowClosing

    private void resetComponents() {
        System.out.println("Resetando componentes...");

        jComboBoxTipoOcorrencia.setSelectedIndex(-1);
        jTextFieldLongitude.setText("");
        jTextFieldLatitude.setText("");
        jTextAreaDescricao.setText("");

        jComboBoxTipoOcorrencia.requestFocus();
    }

    public final void updateTipoOCorrencia() {
        System.out.println("Atualizando JComboBoxTipo...");
        tipos = bd.getListaTipos();
        if (tipos != null) {
            jComboBoxTipoOcorrencia.removeAllItems();
            for (TipoOcorrencia d : tipos) {
                jComboBoxTipoOcorrencia.addItem(d.getDescricao());
            }
        } else {
            System.out.println("Nenhuma ocorrência encontrada");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarOcorrencia;
    private javax.swing.JButton jButtonCadastrarTipo;
    private javax.swing.JComboBox jComboBoxTipoOcorrencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    // End of variables declaration//GEN-END:variables
}
